### ISSUE TITLE
Fix Point System

### ISSUE THREAD

**Issue by kadeska** [kadeska/point_shop_plugin#1]
need to fix the point system. the points do not add and makes two entries in the config.

**Comment by SparklingComet** [comment]
Do you have an idea of what class may be causing this? For example, what's the class making the config entry?

**Comment by kadeska** [comment]
theis class files are making the entry https://github.com/kadeska/point_shop_plugin/blob/master/src/me/PointShop/PlayerJoinListener.java
https://github.com/kadeska/point_shop_plugin/blob/master/src/me/PointShop/Managers.java

**Comment by SparklingComet** [comment]
When removing a config key, try setting it null instead of 0.

**Comment by kadeska** [comment]
fixed!!

**Comment by SparklingComet** [comment]
Fixed?
