### ISSUE TITLE
Coders wanted

### ISSUE THREAD

**Issue by kadeska** [kadeska/point_shop_plugin#5]
I am a beginner for java and spigot API. I would like it if i could get some coders to help with bugs and issues with the plugin.

P.S. I do have some knowledge of java, still learning, and love to learn more. if any one knows of good resources for learning more java and the Spigot API then please, let me know about them.

**Comment by ShanerX** [comment]
I learned the API watching vids from Pogostick29

If you want to improve your Java skills, try with a text book. (Free online pdf)

**Comment by kadeska** [comment]
Thanks, i might look into the text book. I just don't have a lot of time, since I am still in school. Thank you.

Still looking for help, and or info.

**Comment by kadeska** [comment]
BUMP, yes i am still active. just not coding as much as i want because i am still in school.  I will be updating this code soon. stay on the lookout.
